### ISSUE TITLE
作成された仮想環境の名前が自動で変わらない。

### ISSUE THREAD

**Issue by TakumiKishimoto** [C-Naoki/my-python-template#1]
以下のnameの部分を含めた環境名を指す部分が自動でディレクトリ名とかに変わってくれると嬉しい。

[tool.poetry]
name = "my-python-templete"
version = "0.1.0"
description = ""
authors = ["naoki <74347818+C-naoki@users.noreply.github.com>"]
readme = "README.md"

**Comment by C-Naoki** [comment]
[pyclone](https://github.com/C-Naoki/pyclone)の方に実装しました。
